/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashImport } from './routes/_dash'
import { Route as IndexImport } from './routes/index'
import { Route as DashDashIndexImport } from './routes/_dash/dash/index'
import { Route as DashDashCityIndexImport } from './routes/_dash/dash/$city/index'

// Create/Update Routes

const DashRoute = DashImport.update({
  id: '/_dash',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashDashIndexRoute = DashDashIndexImport.update({
  path: '/dash/',
  getParentRoute: () => DashRoute,
} as any)

const DashDashCityIndexRoute = DashDashCityIndexImport.update({
  path: '/dash/$city/',
  getParentRoute: () => DashRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashImport
      parentRoute: typeof rootRoute
    }
    '/_dash/dash/': {
      id: '/_dash/dash/'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashDashIndexImport
      parentRoute: typeof DashImport
    }
    '/_dash/dash/$city/': {
      id: '/_dash/dash/$city/'
      path: '/dash/$city'
      fullPath: '/dash/$city'
      preLoaderRoute: typeof DashDashCityIndexImport
      parentRoute: typeof DashImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  DashRoute: DashRoute.addChildren({
    DashDashIndexRoute,
    DashDashCityIndexRoute,
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_dash"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_dash": {
      "filePath": "_dash.tsx",
      "children": [
        "/_dash/dash/",
        "/_dash/dash/$city/"
      ]
    },
    "/_dash/dash/": {
      "filePath": "_dash/dash/index.tsx",
      "parent": "/_dash"
    },
    "/_dash/dash/$city/": {
      "filePath": "_dash/dash/$city/index.tsx",
      "parent": "/_dash"
    }
  }
}
ROUTE_MANIFEST_END */
